---
title: "Homework 2 Final Summary"
author: "Emma Sayre & Elena Nirgiotis"
date: May 6, 2026
format: html
editor: visual
---

## Summary of Findings 

```{r}
#| label: load_libs
#| include: false
#| echo: false
#| message: false
#| warning: false

#install.packages("dataRetrieval")
library(dataRetrieval)
library(tidyverse)
library(here)
library(patchwork)
```

```{r}
#| label: upload_data
#| include: false
#| echo: false
#| message: false
#| warning: false

#install.packages("dataRetrieval")
library(dataRetrieval)
library(tidyverse)
library(here)
library(patchwork)

siteNumbers <- c("14211720", "14211010", "14166000")
parameterCd <- "00010"  # water temperature
startDate <- "2010-01-01"
endDate <- "2023-12-31"

temp_data <- readNWISdv(siteNumbers, parameterCd, startDate, endDate)
temp_data <- temp_data [ ,-5]

# rename columns for clarity
colnames(temp_data) <- c("agency_cd", "site_no", "Date", "temp_C")

# extract some date info for use later
temp_data$month = month(temp_data$Date, label=TRUE)
temp_data$year = year(temp_data$Date)
view(temp_data)

temp_data$month <- month(temp_data$Date, label=TRUE)
temp_data$year  <- year(temp_data$Date)
write_csv(temp_data, here("temp_data.csv"))
```

```{r}
#| label: June_Temp_Trends
#| include: true
#| echo: false
#| message: false
#| warning: false

june_data <- subset(temp_data, month == "Jun")

june_model <- glm(temp_C ~ year * site_no, data = june_data)
summary(june_model)

june_avg <- june_data |>
  group_by(year, site_no) |>
  summarize(mean_temp = mean(temp_C, na.rm = TRUE))

```

```{r}
#| label: Dec_Temp_Trends
#| include: false
#| echo: false
#| message: false
#| warning: false

library(tidyverse)
# filter for December temperatures
dec_data <- subset(temp_data, month == "Dec")

dec_summary <- dec_data |>
  group_by(year, site_no) |>
  summarize(mean_temp = mean(temp_C, na.rm=TRUE))

# fit a GLM model to see if there is a trend in Dec temperatures over time, separated by sit
dec_model <- glm(temp_C ~ year*site_no, data = dec_data)
summary(dec_model)

```

#### Comparing June and December Temperature Trends

```{r}
#| label: Temp_Comparison 
#| include: false
#| echo: false 
#| message: false
#| warning: false

june_plot <- ggplot(june_avg, aes(x = year, y = mean_temp, color = site_no)) +
  geom_line(alpha = 0.5) +
  geom_point(size = 0.8) +
  geom_smooth(method = "lm", se = FALSE) +
  labs(title = "Mean June Temperature by Site (2010–2023)",
       x = "Year", y = "Mean Temperature (°C)", color = "Site") +
  theme_minimal()

dec_plot <- ggplot(dec_summary, 
                   aes(x=year, y=mean_temp, color=site_no)) + 
  geom_line(alpha=0.5) +
  geom_point(size=0.8) +
  geom_smooth(method = "lm", se = FALSE) +
  labs(title="Mean December Temperature by Site (2010-2023)", 
       x="Year", y="Mean Temperature (°C)", color="Site Number") +
  theme_minimal()

june_plot + dec_plot
```
