---
title: "Emma_Elena_Hw2"
author: "Emma Sayre & Elena Nirgiotis"
date: May 4, 2026
format: html
editor: visual
params:
  use_local_data: true        # Set to FALSE to access the NWIS server
  local_file: "temp_data.csv" 
  site_ids:
  - "4211720"
  - "14211010"
  - "14166000" 
---

**Upload & Clean Data**

```{r}
#| label: upload_data
#| include: true
#| echo: true
#| message: false
#| warning: false

#install.packages("dataRetrieval")
library(dataRetrieval)
library(tidyverse)
library(here)
library(patchwork)

siteNumbers <- c("14211720", "14211010", "14166000")
parameterCd <- "00010"  # water temperature
startDate <- "2010-01-01"
endDate <- "2023-12-31"

temp_data <- readNWISdv(siteNumbers, parameterCd, startDate, endDate)
temp_data <- temp_data [ ,-5]

# rename columns for clarity
colnames(temp_data) <- c("agency_cd", "site_no", "Date", "temp_C")

# extract some date info for use later
temp_data$month = month(temp_data$Date, label=TRUE)
temp_data$year = year(temp_data$Date)
view(temp_data)

temp_data$month <- month(temp_data$Date, label=TRUE)
temp_data$year  <- year(temp_data$Date)
write_csv(temp_data, here("temp_data.csv"))

```

**Plot Data**

```{r}
#| label: plot_data
#| include: true
#| echo: true
#| message: false
#| warning: false

# check by plotting
ggplot(temp_data, aes(x=Date, y=temp_C, color=site_no)) +
  geom_line() +
  labs(title="Stream Temperature at Willamette River Sites",
       x="Date", y="Temperature (°C)", color="Site Number") +
  theme_minimal()



```

**Summary Statistics**

```{r}
#| label: summary_stats
#| include: true
#| echo: true
#| message: false
#| warning: false

yearly_summary <- temp_data |>
  group_by(year,site_no) |>
  summarize(
    mean_temp = mean(temp_C, na.rm = TRUE),
    min_temp  = min(temp_C,  na.rm = TRUE),
    max_temp  = max(temp_C,  na.rm = TRUE))



```
